compatibilityVersion: naiscript-1.0
id: 781dc32b-fb21-424a-a691-46b353d3f195
name: Pixu
createdAt: 1769472066
updatedAt: 1769546200
version: 0.1.1
author: Noble
memoryLimit: 64
description: Helper to be used alongside the Pixu for NovelAI extension.
